os:
  linux

dist:
  trusty

sudo:
  false

language:
  node_js

node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "lts/*"

matrix:
  include:
    - os:
        linux
      dist:
        trusty
      sudo:
        false
      addons:
        chrome:
          stable
        firefox:
          latest
      node_js:
        - "lts/*"
      env:
        - BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless
      script:
        - npm run test:browser
    - os:
        osx
      osx_image:
        xcode9.3
      node_js:
        - "lts/*"
      env:
        - BROWSERS=Safari
      script:
        npm run test:browser
    - os:
        osx
      osx_image:
        xcode9.2
      node_js:
        - "lts/*"
      env:
        - BROWSERS=Safari
      script:
        - npm run test:browser

git:
  depth:
    3

cache:
  directories:
    - node_modules

notifications:
  email:
    false
