os:
  linux

dist:
  trusty

sudo:
  false

addons:
  chrome:
    stable
  firefox:
    latest

matrix:
  include:
    - os:
        osx
      osx_image:
        xcode9.3beta
      node_js:
        - "lts/*"
      env:
        - BROWSERS=Safari
    - os:
        osx
      osx_image:
        xcode9.2
      node_js:
        - "lts/*"
      env:
        - BROWSERS=Safari

language:
  node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"
  - "lts/*"

env:
  - BROWSERS=Chrome,Firefox

git:
  depth:
    3

cache:
  directories:
    - node_modules

notifications:
  email:
    false

script:
  - npm run test:travis
